// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4N2ceq45QNRvnUE_N0_-t1mBY-y_H1Ok',
    appId: '1:763952289739:web:4e09be72136a346f31884e',
    messagingSenderId: '763952289739',
    projectId: 'atual-a0c17',
    authDomain: 'atual-a0c17.firebaseapp.com',
    storageBucket: 'atual-a0c17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGjxyc9ZwMn_n8in5PdWLIMmUOUnb22A',
    appId: '1:763952289739:android:242111a21b8ec36e31884e',
    messagingSenderId: '763952289739',
    projectId: 'atual-a0c17',
    storageBucket: 'atual-a0c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHpkwl1CukRt6v72pIi2G3aJi3fszDzn8',
    appId: '1:763952289739:ios:15c78a7533dc634b31884e',
    messagingSenderId: '763952289739',
    projectId: 'atual-a0c17',
    storageBucket: 'atual-a0c17.firebasestorage.app',
    iosBundleId: 'com.example.gestorCalcadosNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHpkwl1CukRt6v72pIi2G3aJi3fszDzn8',
    appId: '1:763952289739:ios:15c78a7533dc634b31884e',
    messagingSenderId: '763952289739',
    projectId: 'atual-a0c17',
    storageBucket: 'atual-a0c17.firebasestorage.app',
    iosBundleId: 'com.example.gestorCalcadosNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4N2ceq45QNRvnUE_N0_-t1mBY-y_H1Ok',
    appId: '1:763952289739:web:ecdf0fb0fda2d38231884e',
    messagingSenderId: '763952289739',
    projectId: 'atual-a0c17',
    authDomain: 'atual-a0c17.firebaseapp.com',
    storageBucket: 'atual-a0c17.firebasestorage.app',
  );
}
